version: "3.8"
services:
  db:
    build: ./mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
    ports:
      - "3308:3306"
    volumes:
      - ./mariadb:/docker-entrypoint-initdb.d:ro
  server:
    build: ./apache
    restart: always
    volumes:
      - ./apache:/usr/local/apache2/htdocs/
    ports:
      - "8081:80"
